sudo: required
services:
  - docker

before_install:
  - docker build -t rproque/travis:react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rproque/travis:react-test npm test

after_success:
  - docker build -t rproque/travis:multi-client ./client
  - docker build -t rproque/travis:multi-nginx ./nginx
  - docker build -t rproque/travis:multi-server ./server
  - docker build -t rproque/travis:multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push rproque/travis:multi-client
  - docker push rproque/travis:multi-nginx
  - docker push rproque/travis:multi-server
  - docker push rproque/travis:multi-worker